layout_spectrum: 0.7493734
name: knitmodern
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.1806605
  lightness: 0.7580101
  saturation: 0.651792
  rhythmicContrast: 0.9160401
  brandColors:
    - '#FFFFFF'
    - '#020200'
    - '#8F5A4C'
    - '#A2B1CE'
    - '#7D8FA5'
typography_spectrum: 0.3812525
