layout_spectrum: 0.3170426
name: knitmodern
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.1806605
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
  brandColors:
    - '#FFFFFF'
    - '#020200'
    - '#8F5A4C'
    - '#A2B1CE'
    - '#7D8FA5'
typography_spectrum: 0.05513784
